# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#   5.times do |i|
#     Product.create(name: "Product ##{i}", description: "A product.")
#   end

@store1 = Store.create(name: 'Fluminense', description: 'Loja perto da Faculdade Redentor', latitude: '-21.1963157', longitude: '-41.906837')
@store2 = Store.create(name: 'Minha casa', description: 'Somente para testes', latitude: '-21.1960885', longitude: '-41.9023717')

#mercearia
@produto1 = Product.create(name: "Arroz", alias: "")
@produto2 = Product.create(name: "Feijão", alias: "")
@produto3 = Product.create(name: "Grão de bico", alias: "")
@produto4 = Product.create(name: "Óleo", alias: "")
@produto5 = Product.create(name: "Farinha", alias: "de trigo")
@produto6 = Product.create(name: "Farinha", alias: "de rosca")
@produto7 = Product.create(name: "Açucar", alias: "")
@produto8 = Product.create(name: "Milho", alias: "Verde")
@produto9 = Product.create(name: "Extrato de tomate", alias: "")
@produto10 = Product.create(name: "Molho", alias: "")
@produto11 = Product.create(name: "Vinagre", alias: "")
@produto12 = Product.create(name: "Azeite", alias: "de Oliva")
@produto13 = Product.create(name: "Ervilha", alias: "")
@produto14 = Product.create(name: "Pepino", alias: "")
@produto15 = Product.create(name: "Palmito", alias: "")
@produto16 = Product.create(name: "Fermento", alias: "")
#lanche
@produto17 = Product.create(name: "Café", alias: "")
@produto18 = Product.create(name: "Chá", alias: "")
@produto19 = Product.create(name: "Bolos", alias: "")
@produto20 = Product.create(name: "Cereal", alias: "")
@produto21 = Product.create(name: "Mel", alias: "")
@produto22 = Product.create(name: "Biscoito", alias: "")
@produto23 = Product.create(name: "Pào", alias: "")
@produto24 = Product.create(name: "Achocolatado", alias: "")
#temperos
@produto25 = Product.create(name: "Maionese", alias: "")
@produto26 = Product.create(name: "Catchup", alias: "")
@produto27 = Product.create(name: "Mostarda", alias: "")
@produto28 = Product.create(name: "Pimenta", alias: "")
@produto29 = Product.create(name: "Sal", alias: "")
@produto30 = Product.create(name: "Louro", alias: "")
@produto31 = Product.create(name: "Orégano", alias: "")
@produto32 = Product.create(name: "Colorau", alias: "")
@produto33 = Product.create(name: "Salsa", alias: "")
@produto34 = Product.create(name: "Alho", alias: "")
#enlatados
@produto35 = Product.create(name: "Creme de leite", alias: "")
@produto36 = Product.create(name: "Leite condensado", alias: "")
@produto37 = Product.create(name: "Salsicha", alias: "")
@produto38 = Product.create(name: "Atum", alias: "")
@produto39 = Product.create(name: "Sardinha", alias: "")
@produto40 = Product.create(name: "Cogumelo", alias: "")
@produto41 = Product.create(name: "Azeitona", alias: "")
#enlatados
@produto42 = Product.create(name: "Amendoin", alias: "")
@produto43 = Product.create(name: "Milho", alias: "para Pipoca")
#laticinios
@produto44 = Product.create(name: "Leite", alias: "")
@produto45 = Product.create(name: "Iorgute", alias: "")
@produto46 = Product.create(name: "Manteiga", alias: "")
@produto47 = Product.create(name: "Margarina", alias: "")
#queijos
@produto48 = Product.create(name: "Mussarela", alias: "")
@produto49 = Product.create(name: "Queijo", alias: "")

@produto50 = Product.create(name: "Sorvete", alias: "")
@produto51 = Product.create(name: "Pizza", alias: "")
@produto52 = Product.create(name: "Pão", alias: "de Forma")


Price.create(store_id: @store1.id, product_id: @produto1.id, price: 9.75)
Price.create(store_id: @store1.id, product_id: @produto2.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto3.id, price: 9.75)
Price.create(store_id: @store1.id, product_id: @produto4.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto5.id, price: 9.75)
Price.create(store_id: @store1.id, product_id: @produto6.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto7.id, price: 9.75)
Price.create(store_id: @store1.id, product_id: @produto8.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto9.id, price: 9.75)
Price.create(store_id: @store1.id, product_id: @produto10.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto11.id, price: 9.75)
Price.create(store_id: @store1.id, product_id: @produto12.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto13.id, price: 9.75)
Price.create(store_id: @store1.id, product_id: @produto14.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto15.id, price: 9.75)
Price.create(store_id: @store1.id, product_id: @produto16.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto17.id, price: 9.75)
Price.create(store_id: @store1.id, product_id: @produto18.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto19.id, price: 9.75)
Price.create(store_id: @store1.id, product_id: @produto20.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto21.id, price: 9.75)
Price.create(store_id: @store1.id, product_id: @produto22.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto23.id, price: 9.75)
Price.create(store_id: @store1.id, product_id: @produto24.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto25.id, price: 9.75)
Price.create(store_id: @store1.id, product_id: @produto26.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto27.id, price: 9.75)
Price.create(store_id: @store1.id, product_id: @produto28.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto29.id, price: 9.75)
Price.create(store_id: @store1.id, product_id: @produto30.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto31.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto32.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto33.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto34.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto35.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto36.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto37.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto38.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto39.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto40.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto41.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto42.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto43.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto44.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto45.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto46.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto47.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto48.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto49.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto50.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto51.id, price: 4.32)
Price.create(store_id: @store1.id, product_id: @produto52.id, price: 4.32)

List.create(store_id: @store1.id, name: 'Compar no Sábado')


